# Generated by Django 2.2 on 2019-04-23 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IP_public_used',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.CharField(max_length=255, null=True)),
                ('client', models.CharField(max_length=255, null=True)),
                ('date_start', models.DateTimeField()),
                ('date_expire', models.DateTimeField()),
                ('price_bought', models.BigIntegerField()),
                ('price_sold', models.BigIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IP_public_available',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.CharField(max_length=255, null=True)),
                ('date_start', models.DateTimeField()),
                ('date_expire', models.DateTimeField()),
                ('price_bought', models.BigIntegerField()),
                ('price_to_sell', models.BigIntegerField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IP_private_used',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.CharField(max_length=255, null=True)),
                ('Device', models.CharField(max_length=255, null=True)),
                ('date_start', models.DateTimeField()),
                ('date_expire', models.DateTimeField()),
                ('price_bought', models.BigIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
